---
apiVersion: v1
data:
  ALLOW_SELF_SIGNED_ISSUER: "true"
  ENABLE_M2M_TOKENS: "true"
  EXTRA_JWT_ISSUERS: https://kubernetes.default.svc.cluster.local=https://kubernetes.default.svc.cluster.local
  FORCE_HTTPS: "false"
kind: ConfigMap
metadata:
  name: oauth2-proxy-parameters
