---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: self-signed-kubernetes-oidc-issuer-configurator
  namespace: kaas-istio
rules:
- apiGroups:
  - security.istio.io
  resources:
  - requestauthentications
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: self-signed-kubernetes-oidc-issuer-configurator
  namespace: kaas-istio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: self-signed-kubernetes-oidc-issuer-configurator
subjects:
- kind: ServiceAccount
  name: self-signed-kubernetes-oidc-issuer-configurator
  namespace: kaas-istio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unauthenticated-oidc-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:service-account-issuer-discovery
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:unauthenticated
