---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::028257207274:role/oidc-test
  name: self-signed-kubernetes-oidc-issuer-configurator
  namespace: kaas-istio
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth2-proxy
